# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
