# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0004_likemodel_has_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='has_liked',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
